#ifndef CPP_NOT_SO_SIMPLE_CALCULATOR_SLOTHS_PARTTYPE_H
#define CPP_NOT_SO_SIMPLE_CALCULATOR_SLOTHS_PARTTYPE_H

enum PartType {
    NUMBER = 0,
    ADDITION = 1,
    SUBTRACTION = 1,
    DIVISION = 2,
    MULTIPLICATION = 2,
    POWER = 3,
    ROOT = 3
};

#endif //CPP_NOT_SO_SIMPLE_CALCULATOR_SLOTHS_PARTTYPE_H
