#ifndef CPP_NOT_SO_SIMPLE_CALCULATOR_SLOTHS_PARTTYPE_H
#define CPP_NOT_SO_SIMPLE_CALCULATOR_SLOTHS_PARTTYPE_H

enum PartType {
    NUMBER,
    ADDITION,
    SUBTRACTION,
    DIVISION,
    MULTIPLICATION,
    POWER,
    ROOT,
    INVALID
};

#endif //CPP_NOT_SO_SIMPLE_CALCULATOR_SLOTHS_PARTTYPE_H
